name: flutter_lib
description: A new flutter module project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  scoped_model: ^0.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  module:
    androidPackage: info.kitproject.flutterkotlin.flutterlib
    iosBundleIdentifier: info.kitproject.flutterkotlin.flutterLib
